### ISSUE TITLE
Meta-issue for next season

### ISSUE THREAD

**Issue by arbimo** [insa-4ir-meta-heuristiques/template-jobshop#3]
## Quantité de code

Le projet à beaucoup de code ce qui laisse les étudiants un peu perdu et nous force à fournir beaucoup de documentations et d'explication prélable

- [ ] Retirer l'encodage `JobNumbers`

## Difficultés avec EST

- [ ] `ResourceOrder` calcule directement les instants de début pour les tâches déjà insérées. 

Cela permettrait aux étudiants de ne pas avoir à gérer le maintien des instants de début/fin pour chaque job/machine dans l'implémentation de GreedySolver. Il faudrait simplement faire le max des deux valeurs

## Difficultés avec les génériques en Java

Les étudiants ont des difficultés à comprendre les génériques dans le package `neighborhood`.

- [ ] Option 1 : Supprimer les génériques (que l'on utilise pas vraiment et qui ne seraient pas très pertinent si on supprime JobNumbers).
- [ ] Option 2 : Documenter cette classe et ses utilisations.

## Difficultés avec le taboo

En l'état actuel, la solution que l'on propose pour gérer la liste taboo n'est pas forcément très intuitive et peut être sujet à erreur.

- [ ] Orienter les étudiants vers un RingBuffer à capacité fixe. Pour éviter une recherche linéaire dans la liste elle peut être combinée avec un HashSet pour tester la présence en O(1). (Peut être laissé en option car le coût sera vraisemblablement dominé par la construction du voisin et de son `Schedule`)

Cette solution présente l'avantage d'être plus en phase avec l'esprit du Taboo.

## Misc

- [ ] Renommer `Neighbor` en `Move`. Ce n'est pas directement un voisin mais un changement à apporter à une solution.
- [ ] Favoriser les données immuables. C'est en général une très bonne pratique (sur laquelle on insiste en programmation fonctionnelle), qui rapproche le code du modèle mathématique et évite les gestions d'état qui peuvent être difficile à débugger. 
- [ ] Documenter l'usage du mot clé `final`
- [ ] Éviter les `static inner classes` (Swap, Block) et les placer directement dans le package
- [ ] configurer le CI pour automatiquement publier la documentation (attention: ne doit pas se lancer sur les dépôts clonés par les étudiants)
